In [7]:
import pandas as pd

In [8]:
dataf=pd.read_csv(r"C:\Users\jella sreeja\OneDrive\Desktop\PROJECT\data\diabetes_dataset.csv\diabetes_dataset.csv")
dataf

,year,gender,age,location,race:AfricanAmerican,race:Asian,race:Caucasian,race:Hispanic,race:Other,hypertension,heart_disease,smoking_history,bmi,hbA1c_level,blood_glucose_level,diabetes
0,2020,Female,32.0,Alabama,0,0,0,0,1,0,0,never,27.32,5.0,100,0
1,2015,Female,29.0,Alabama,0,1,0,0,0,0,0,never,19.95,5.0,90,0
2,2015,Male,18.0,Alabama,0,0,0,0,1,0,0,never,23.76,4.8,160,0
3,2015,Male,41.0,Alabama,0,0,1,0,0,0,0,never,27.32,4.0,159,0
4,2016,Female,52.0,Alabama,1,0,0,0,0,0,0,never,23.75,6.5,90,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2018,Female,33.0,Wyoming,0,0,0,0,1,0,0,never,21.21,6.5,90,0
99996,2016,Female,80.0,Wyoming,0,1,0,0,0,0,0,No Info,36.66,5.7,100,0
99997,2018,Male,46.0,Wyoming,0,1,0,0,0,0,0,ever,36.12,6.2,158,0
99998,2018,Female,51.0,Wyoming,1,0,0,0,0,0,0,not current,29.29,6.0,155,0
99999,2016,Male,13.0,Wyoming,0,0,0,1,0,0,0,No Info,17.16,5.0,90,0

In [9]:
dataf.head()

,year,gender,age,location,race:AfricanAmerican,race:Asian,race:Caucasian,race:Hispanic,race:Other,hypertension,heart_disease,smoking_history,bmi,hbA1c_level,blood_glucose_level,diabetes
0,2020,Female,32.0,Alabama,0,0,0,0,1,0,0,never,27.32,5.0,100,0
1,2015,Female,29.0,Alabama,0,1,0,0,0,0,0,never,19.95,5.0,90,0
2,2015,Male,18.0,Alabama,0,0,0,0,1,0,0,never,23.76,4.8,160,0
3,2015,Male,41.0,Alabama,0,0,1,0,0,0,0,never,27.32,4.0,159,0
4,2016,Female,52.0,Alabama,1,0,0,0,0,0,0,never,23.75,6.5,90,0

In [10]:
dataf.shape

(100000, 16)

In [11]:
dataf.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   year                  100000 non-null  int64
 1   gender                100000 non-null  str
 2   age                   100000 non-null  float64
 3   location              100000 non-null  str
 4   race:AfricanAmerican  100000 non-null  int64
 5   race:Asian            100000 non-null  int64
 6   race:Caucasian        100000 non-null  int64
 7   race:Hispanic         100000 non-null  int64
 8   race:Other            100000 non-null  int64
 9   hypertension          100000 non-null  int64
 10  heart_disease         100000 non-null  int64
 11  smoking_history       100000 non-null  str
 12  bmi                   100000 non-null  float64
 13  hbA1c_level           100000 non-null  float64
 14  blood_glucose_level   100000 non-null  int64
 15  diabetes              100000 non-null  int64
dtypes: float64(3), int64(10), str(3)
memory usage: 12.2 MB

In [12]:
dataf.describe()

,year,age,race:AfricanAmerican,race:Asian,race:Caucasian,race:Hispanic,race:Other,hypertension,heart_disease,bmi,hbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2018.360820,41.885856,0.202230,0.200150,0.198760,0.19888,0.199980,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,1.345239,22.516840,0.401665,0.400114,0.399069,0.39916,0.399987,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,2015.000000,0.080000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,2019.000000,24.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,2019.000000,43.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,2019.000000,60.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,2022.000000,80.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [13]:
print(dataf.isna().sum())

year                    0
gender                  0
age                     0
location                0
race:AfricanAmerican    0
race:Asian              0
race:Caucasian          0
race:Hispanic           0
race:Other              0
hypertension            0
heart_disease           0
smoking_history         0
bmi                     0
hbA1c_level             0
blood_glucose_level     0
diabetes                0
dtype: int64

In [14]:
print((dataf == 0).sum())

year                        0
gender                      0
age                         0
location                    0
race:AfricanAmerican    79777
race:Asian              79985
race:Caucasian          80124
race:Hispanic           80112
race:Other              80002
hypertension            92515
heart_disease           96058
smoking_history             0
bmi                         0
hbA1c_level                 0
blood_glucose_level         0
diabetes                91500
dtype: int64

In [15]:
print(((dataf == 0).mean()*100).round(2))

year                     0.00
gender                   0.00
age                      0.00
location                 0.00
race:AfricanAmerican    79.78
race:Asian              79.98
race:Caucasian          80.12
race:Hispanic           80.11
race:Other              80.00
hypertension            92.52
heart_disease           96.06
smoking_history          0.00
bmi                      0.00
hbA1c_level              0.00
blood_glucose_level      0.00
diabetes                91.50
dtype: float64

In [16]:
invalid_rows = dataf[['race:AfricanAmerican','race:Asian','race:Caucasian','race:Hispanic','race:Other']].sum(axis=1) != 1
print("Rows with invalid race encoding:", invalid_rows.sum())

Rows with invalid race encoding: 0

In [1]:

from sklearn.preprocessing import LabelEncoder

# 1. Encode gender
le = LabelEncoder()
dataf['gender_encoded'] = le.fit_transform(dataf['gender'])  # Female=0, Male=1

# 2. One-hot encode smoking_history
##dataf = pd.get_dummies(dataf, columns=['smoking_history'], prefix='smoke')

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
dataf.head()

,year,gender,age,location,race:AfricanAmerican,race:Asian,race:Caucasian,race:Hispanic,race:Other,hypertension,...,hbA1c_level,blood_glucose_level,diabetes,gender_encoded,smoke_No Info,smoke_current,smoke_ever,smoke_former,smoke_never,smoke_not current
0,2020,Female,32.0,Alabama,0,0,0,0,1,0,...,5.0,100,0,0,False,False,False,False,True,False
1,2015,Female,29.0,Alabama,0,1,0,0,0,0,...,5.0,90,0,0,False,False,False,False,True,False
2,2015,Male,18.0,Alabama,0,0,0,0,1,0,...,4.8,160,0,1,False,False,False,False,True,False
3,2015,Male,41.0,Alabama,0,0,1,0,0,0,...,4.0,159,0,1,False,False,False,False,True,False
4,2016,Female,52.0,Alabama,1,0,0,0,0,0,...,6.5,90,0,0,False,False,False,False,True,False

In [ ]:
dataf[['gender', 'gender_encoded']].head()
dataf.filter(like='smoke_').head()

,smoke_No Info,smoke_current,smoke_ever,smoke_former,smoke_never,smoke_not current
0,False,False,False,False,True,False
1,False,False,False,False,True,False
2,False,False,False,False,True,False
3,False,False,False,False,True,False
4,False,False,False,False,True,False